# Generated by Django 3.0.3 on 2020-02-23 17:42

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outcome',
            options={'ordering': ['proposition', 'code']},
        ),
        migrations.AlterModelManagers(
            name='tokens',
            managers=[
                ('tokens', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='proposition',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
