# Generated by Django 3.0.3 on 2020-02-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_auto_20200223_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposition',
            name='time',
        ),
        migrations.AddField(
            model_name='proposition',
            name='creation_date',
            field=models.DateField(null=True),
        ),
    ]
