# Generated by Django 2.2.4 on 2019-10-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_auto_20191012_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balance',
            options={'ordering': ['user', 'commodity']},
        ),
        migrations.AlterModelOptions(
            name='commodity',
            options={'ordering': ['resolved', 'resolves_on', 'code'], 'verbose_name_plural': 'Commodities'},
        ),
        migrations.AlterModelOptions(
            name='deposit',
            options={'ordering': ['user', 'time']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['user']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['type', 'price', 'remaining_amount']},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='resolution',
            options={'ordering': ['user', 'time']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['commodity', 'time']},
        ),
        migrations.AlterModelOptions(
            name='withdrawal',
            options={'ordering': ['user', 'time']},
        ),
        migrations.AddField(
            model_name='commodity',
            name='code',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
    ]
