# Generated by Django 3.0.3 on 2020-02-23 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0003_auto_20200223_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposition',
            name='creation_date',
            field=models.DateField(auto_now=True, default=datetime.datetime(2020, 2, 23, 17, 47, 48, 15158), help_text='The date on which this proposition was created.'),
            preserve_default=False,
        ),
    ]
