# Generated by Django 2.2.4 on 2019-10-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0003_auto_20191012_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['affirmative', 'price', 'remaining_quantity']},
        ),
        migrations.RenameField(
            model_name='balance',
            old_name='type',
            new_name='affirmative',
        ),
        migrations.RenameField(
            model_name='balance',
            old_name='amount',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='deposit',
            old_name='amount',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='type',
            new_name='affirmative',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='remaining_amount',
            new_name='remaining_quantity',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total_amount',
            new_name='total_quantity',
        ),
        migrations.RenameField(
            model_name='resolution',
            old_name='award',
            new_name='payout',
        ),
        migrations.RenameField(
            model_name='resolution',
            old_name='amount',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='withdrawal',
            old_name='amount',
            new_name='value',
        ),
        migrations.AlterField(
            model_name='commodity',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
