# Generated by Django 3.0.3 on 2020-02-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0004_auto_20200223_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposition',
            name='creation_date',
            field=models.DateField(help_text='The date on which this proposition was created.'),
        ),
    ]
