# Generated by Django 3.0.3 on 2020-03-02 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0005_auto_20200224_1154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['proposition', '-time']},
        ),
        migrations.AlterModelOptions(
            name='tokens',
            options={'ordering': ['user', 'quantity', 'proposition'], 'verbose_name_plural': 'tokens'},
        ),
    ]
