# Generated by Django 2.2.4 on 2019-10-13 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0006_auto_20191013_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposition',
            options={'ordering': ['resolved', 'resolves_on', 'label'], 'verbose_name_plural': 'Propositions'},
        ),
    ]
