# Generated by Django 2.2.4 on 2019-10-13 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0007_auto_20191013_2145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['proposition', '-time']},
        ),
    ]
