# Generated by Django 2.2.6 on 2019-10-17 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0009_auto_20191015_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['affirmative', '-price', 'quantity']},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='remaining_quantity',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_quantity',
        ),
    ]
