# Generated by Django 3.0.3 on 2020-03-02 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0010_auto_20200302_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposition',
            options={},
        ),
    ]
