# Generated by Django 2.2.6 on 2019-10-21 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0011_auto_20191020_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funds',
            options={'ordering': ['user']},
        ),
    ]
