# Generated by Django 2.2.6 on 2019-10-21 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0014_auto_20191021_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funds',
            options={},
        ),
    ]
