# Generated by Django 2.2.6 on 2019-10-21 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0016_auto_20191021_1327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funds',
            options={'ordering': ['user'], 'verbose_name_plural': 'funds'},
        ),
    ]
