# Generated by Django 2.2.6 on 2019-10-21 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0017_auto_20191021_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='user',
        ),
        migrations.DeleteModel(
            name='Deposit',
        ),
        migrations.DeleteModel(
            name='Withdrawal',
        ),
    ]
