# Generated by Django 2.2.6 on 2019-10-26 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0019_auto_20191021_2139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['affirmative', '-price', 'time']},
        ),
    ]
