# Generated by Django 2.2.6 on 2019-10-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0020_auto_20191026_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funds',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='resolution',
            name='payout',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
