# Generated by Django 2.2.6 on 2019-10-26 15:33

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('markets', '0021_auto_20191026_0154'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Balance',
            new_name='Stake',
        ),
        migrations.AlterModelOptions(
            name='proposition',
            options={'ordering': ['active', 'resolve_date', 'code']},
        ),
        migrations.AlterModelOptions(
            name='stake',
            options={'ordering': ['user', 'proposition']},
        ),
        migrations.RemoveField(
            model_name='proposition',
            name='affirmative',
        ),
        migrations.RemoveField(
            model_name='proposition',
            name='label',
        ),
        migrations.RemoveField(
            model_name='proposition',
            name='resolved',
        ),
        migrations.RemoveField(
            model_name='proposition',
            name='resolves_on',
        ),
        migrations.AddField(
            model_name='proposition',
            name='active',
            field=models.BooleanField(default=True, help_text='Whether this proposition is still yet to resolve.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposition',
            name='code',
            field=models.CharField(default='ABC', help_text='The three-letter proposition code.', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposition',
            name='resolve_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 26, 15, 33, 5, 172661), help_text='The date on which this proposition will/did resolve.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposition',
            name='result',
            field=models.BooleanField(default=True, help_text='Whether this proposition resolved in favour of the affirmative.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proposition',
            name='description',
            field=models.CharField(help_text='The definitive proposition statement.', max_length=100),
        ),
    ]
