# Generated by Django 2.2.6 on 2019-10-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0023_auto_20191026_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(help_text='The price the user is willing to pay per token.'),
        ),
    ]
