# Generated by Django 2.2.6 on 2019-10-26 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0024_auto_20191026_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['proposition', 'affirmative', '-price', 'time']},
        ),
    ]
