# Generated by Django 2.2.6 on 2019-10-26 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('markets', '0025_auto_20191026_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='no_bidder',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='yes_bidder',
        ),
        migrations.AddField(
            model_name='transaction',
            name='affirmative_user',
            field=models.ForeignKey(default=None, help_text='The user in favour of the affirmative.', on_delete=django.db.models.deletion.CASCADE, related_name='yes_bidder', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='negative_user',
            field=models.ForeignKey(default=None, help_text='The user in favour of the negative.', on_delete=django.db.models.deletion.CASCADE, related_name='no_bidder', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.IntegerField(help_text='The affirmative price at which the tokens were traded.'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='proposition',
            field=models.ForeignKey(help_text='The proposition which was traded.', on_delete=django.db.models.deletion.CASCADE, to='markets.Proposition'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.IntegerField(help_text='The number of tokens which were traded.'),
        ),
    ]
